# Site settings
title: 3D Print Cost Calculator
description: Free online calculator for estimating 3D printing costs including materials, electricity, and labor
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://vishalpatra.github.io" # the base hostname & protocol for your site

# User settings
username: 3D Print Cost Calculator
user_description: Get instant cost estimates for your 3D printing projects
user_title: Calculate Your Printing Costs
email: your-email@domain.com
github_username: vishalpatra

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
