# Site settings
title: 3D Print Cost Calculator
description: A simple and efficient calculator for estimating 3D printing costs
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://vishalpatra.github.io" # the base hostname & protocol for your site

# User settings
username: 3D Print Calculator
user_description: Calculate accurate costs for your 3D printing projects including material, electricity, and labor costs.
user_title: 3D Print Cost Estimator
email: your-email@domain.com
github_username: vishalpatra

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
