# Site settings
title: 8000ers Explorer
description: Interactive Map of the World's Highest Peaks
baseurl: ""
url: "https://vishalpatra.github.io"

# User settings
username: Vishalpatra
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Front-End Developer
email: vishalpatra@outlook.com
twitter_username: notvishalpatra
github_username:  Vishalpatra
gplus_username:  Vishalpatra

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
