# Site settings
title: 3D Print Cost Calculator
description: Free online calculator for estimating 3D printing costs including materials, electricity, and labor
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://3dprintcostcalculator.com" # the base hostname & protocol for your site

# User settings
username: Vishal Patra
user_description: A simple, responsive calculator for estimating 3D printing costs
user_title: 3D Print Cost Calculator
email: your-email@domain.com
github_username: vishalpatra
linkedin_username: vishalpatra
instagram_username: thirddimensionalprints

# Google-analytics
google-analytics:
  id: "G-TCYVDCEP0W"

# Google AdSense
google-adsense:
  publisher-id: "pub-8953007004561903"
  
exclude: ['package.json', 'src' , 'node_modules']
